[package]
name = "bevy-jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = { version = "0.6.1" }
bevy = { version = "0.6.1", features = ["dynamic"] }
bevy_prototype_lyon = "0.4.0"